Bur 43 frontend create responsive header
VTKLeuven/burgieclan pull request #108
Opened 2024-08-07 07:54 UTC by driesvanspauwen

2024-08-28 21:28 UTC, rserry requested changes

2024-08-28 21:28 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                        <a href="profile" className="text-sm font-semibold leading-6 text-gray-900">
redirect to /profile or /account?

2024-08-28 21:28 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                    {/* Mobile menu toggle button */}
This comment is not needed here I think?

2024-08-28 21:28 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                                    href="login"
No check if user is already authenticated, like the desktop version

2024-08-28 21:28 UTC, rserry commented on frontend/src/components/login/LoginForm.tsx
> +import Logo from "@/components/branding/Logo";
unused

2024-08-29 20:51 UTC, driesvanspauwen commented on frontend/src/components/header/Header.tsx
> +                        <a href="profile" className="text-sm font-semibold leading-6 text-gray-900">
account is better

2024-08-29 21:14 UTC, driesvanspauwen commented
comments are resolved, waiting for BUR-168 to release

2024-08-30 14:17 UTC, rserry approved these changes

2024-08-30 14:17 UTC, merged