Bur 183 frontend disable sentry locally
VTKLeuven/burgieclan pull request #116
Opened 2024-08-19 11:03 UTC by driesvanspauwen

2024-08-20 15:19 UTC, rserry requested changes

2024-08-20 15:19 UTC, rserry commented on frontend/sentry.client.config.ts
> +    dsn: "https://c7a1562dd406594aeb3e6d27b13e53bc@o918793.ingest.us.sentry.io/4506733883621376",
Maybe put this value also in a env variable. Backend .env also has one
Then rotate this key if possible

2024-08-20 15:19 UTC, rserry commented on frontend/sentry.server.config.ts
> +    dsn: "https://c7a1562dd406594aeb3e6d27b13e53bc@o918793.ingest.us.sentry.io/4506733883621376",
same for this url, move to .env

2024-08-21 11:19 UTC, driesvanspauwen commented on frontend/sentry.client.config.ts
> +    dsn: "https://c7a1562dd406594aeb3e6d27b13e53bc@o918793.ingest.us.sentry.io/4506733883621376",
i don't think rotating is necessary because it's a public key

2024-08-21 11:22 UTC, merged