Bur 44 frontend create responsive footer
VTKLeuven/burgieclan pull request #118
Opened 2024-08-28 09:13 UTC by driesvanspauwen

2024-08-28 21:20 UTC, rserry requested changes

2024-08-28 21:20 UTC, rserry commented on frontend/src/app/(header-footer)/testtest/page.tsx
maybe remove this page xD

2024-08-28 21:20 UTC, rserry commented on frontend/src/app/layout.tsx
> +import Footer from "@/components/footer/Footer";
not used

2024-08-28 21:20 UTC, rserry commented on frontend/src/components/footer/Footer.tsx
> +                            &copy; 2024 Vlaamse Technische Kring vzw
Can you auto set current year?

2024-08-28 21:20 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                        <a href="profile" className="text-sm font-semibold leading-6 text-gray-900">
redirect to /profile or /account?

2024-08-28 21:20 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                    {/* Mobile menu toggle button */}
This comment is not needed here I think?

2024-08-28 21:20 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                                    href="login"
No check if user is already authenticated, like the desktop version

2024-08-28 21:20 UTC, rserry commented on frontend/tsconfig.json
> +}
why remove newline?

2024-08-28 21:25 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                        <a href="profile" className="text-sm font-semibold leading-6 text-gray-900">
added to PR #108

2024-08-28 21:25 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                                    href="login"
added to PR #108

2024-08-28 21:27 UTC, rserry commented on frontend/src/components/header/Header.tsx
> +                    {/* Mobile menu toggle button */}
added to PR #108

2024-08-29 21:35 UTC, driesvanspauwen commented
PR comments resolved and waiting for BUR-168 to release

2024-08-30 14:19 UTC, rserry approved these changes

2024-08-30 14:19 UTC, merged