BUR-174 download all from course module program
VTKLeuven/burgieclan pull request #131
Opened 2024-11-10 22:34 UTC by rserry

2025-02-01 16:08 UTC, pedrodevog requested changes

2025-02-01 16:08 UTC, pedrodevog commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function createFileResponse(string $fileName): Response
This can be done more efficiently. Right now you are loading everything at once to the server (eg 1GB ZIP file will take up 1GB of memory space on the server). We can use StreamedResponse to handle this in chunks:

return new StreamedResponse(function() use ($fileName) {
    readfile($fileName);
}, 200, [
    'Content-Type' => 'application/zip',
    'Content-Disposition' => 'attachment;filename="document-export-' . 
        (new DateTime())->format('Y-m-d') . '.zip"',
    'Content-Length' => filesize($fileName)
]);

2025-02-01 16:08 UTC, pedrodevog commented on backend/src/Repository/DocumentRepository.php
> +        } catch (NoResultException | NonUniqueResultException $e) {
Add error logging:

catch (NoResultException | NonUniqueResultException $e) {
    $this->logger->warning('Error counting pending documents', [
        'error' => $e->getMessage()
    ]);
    return 0;
}

2025-02-01 16:16 UTC, rserry commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function createFileResponse(string $fileName): Response
What effect has streaming on the server? I assume the $fileName is the name of the zip, so that zip would already exist on the server (and they get reused so no unnecessary recreation of zips is done)

2025-02-01 19:04 UTC, pedrodevog requested changes

2025-02-01 19:04 UTC, pedrodevog commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function generateContentHash(array $programs, array $modules, array $courses): string
Why would you hash based on content? Can't you just use the ids instead? This is more efficient
eg:
private function generateEfficientHash(ZipApi $zipApi): string
{
    // Just use IDs which uniquely identify the content
    $hashData = [
        'programs' => array_map(fn($p) => $p->getId(), $zipApi->programs),
        'modules' => array_map(fn($m) => $m->getId(), $zipApi->modules),
        'courses' => array_map(fn($c) => $c->getId(), $zipApi->courses),
    ];
    
    return md5(json_encode($hashData));
}

2025-02-01 19:04 UTC, pedrodevog commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function createFileResponse(string $fileName): Response
Streaming will read out the created ZIP and then send it in chunks to the user. So we could indeed also improve how the ZIP is created to make it more performant. However, the zipping is already pretty performant since ZipArchive is already optimized for batch operations (actual file content isn't loaded by PHP instead it uses references to the ZIP). Now when we send to the user especially `file_get_contents()` needs the ZIP to fit into PHP memory. If we now have multiple people downloading at the same time this process can crash... With streaming the data flows directly from disk to network, and PHP memory only needs memory for handling the chunks being transferred.

2025-02-13 17:19 UTC, rserry commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function createFileResponse(string $fileName): Response
I added the streamedresponse, but this has to be tested on a proper production server. With big files (5GB) it fills up the memory. This could be because of the symfony development server

2025-02-13 17:23 UTC, rserry commented on backend/src/Controller/Api/DownloadZipController.php
> +    private function generateContentHash(array $programs, array $modules, array $courses): string
This is not sufficiënt. documents could be added, changing the actual content of the zip. Even with id's of documents it is not good enough. A document could be changed, so the id would stay but the actual file would differ. Now, all document names are added to one long string, which is hashed.

2025-02-21 21:32 UTC, pedrodevog approved these changes

2025-02-21 21:35 UTC, merged